.PHONY: clean All

All:
	@echo "----------Building project:[ NewCproject - Debug ]----------"
	@cd "NewCproject" && "$(MAKE)" -f  "NewCproject.mk"
clean:
	@echo "----------Cleaning project:[ NewCproject - Debug ]----------"
	@cd "NewCproject" && "$(MAKE)" -f  "NewCproject.mk" clean
